name: Test KHF
run-name: ${{ github.actor }}

# Trigger on pushes that affect the KHF directory
on:
  push:
    paths:
      - elixir/khf/**

jobs:
  test-khf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.15
      - working-directory: elixir/khf
        run: mix test
